[package]
name = "neural_network"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"

[[example]]
name = "simple_example"
path = "examples/simple_example.rs"

[[example]]
name = "flexible_architecture"
path = "examples/flexible_architecture.rs"
