architecture = [
    3,
    6,
    2,
]
learning_rate = 0.05
hebbian_mode = "Oja"
hebbian_rate = 0.05
anti_hebbian_rate = 0.0
decay_rate = 0.005
homeostatic_rate = 0.005
target_activity = 0.2
history_size = 20
use_backprop = false
backprop_rate = 0.0
online_learning = false

[training]
batch_size = 32
print_interval = 100
early_stop_threshold = 0.001
early_stop_patience = 50
validation_split = 0.2
